_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
